### PR TITLE
add extra_properties, bump gem typhoeus

### PR DESCRIPTION
**Pull request by rus-max**

### CODE REVIEW

**Comment by toothrot** [comment]
Thanks for the PR!

I don't see "extra properties" in the API documentation, only event properties and user properties. What fields does this add? Could you maybe provide a test as an example?

**Comment by shaliko** [comment]
@toothrot Looks like the reason that that request is have ability use more properties from [Amplitude API](https://amplitude.zendesk.com/hc/en-us/articles/204771828).

As example now you can't send "IP" by "amplitude-api" GEM. 

Other missing params "language", "price", "revenue", "location_lat", "location_lng", etc...

**Comment by toothrot** [comment]
Thanks @shaliko! That's what I assumed, I was just making sure I wasn't missing anything. I'm going to address those explicitly in #13 instead

**Comment by shaliko** [comment]
@toothrot I added IP param to Event and did refactoring for easy add more params. Fill free modify that code  https://github.com/toothrot/amplitude-api/pull/14

**Comment by hult** [comment]
I'd love this to be merged, to be able to use the `app_version`, `platform`, `os_name`, `os_version` and `device_*` properties. Any reason not to? (It seems the only reason the build fails is that a line is too long.)

**Comment by kolorahl** [comment]
@hult Actually, there's a new way to allow data into the event payload, which is through the `whitelist` configuration field (see [AmplitudeAPI::Config](https://github.com/toothrot/amplitude-api/blob/master/lib/amplitude_api/config.rb)). This PR can be adjusted to simply include desired fields in the whitelist and then they will be accepted by `AmpiltudeAPI::Event.new`. e.g.

```
whitelist: %i(user_id device_id event_type time
            event_properties user_properties time ip platform country insert_id
            revenue_type price quantity product_id app_version platform os_name
            os_version etc),
```

I plan to expand the whitelist before cutting a new version, but please feel free to do the honors if you have the free time. Once the new version is up then this problem should be fixed regardless, either because the defaults give you access to set those fields or because you will be able to manually set them using `AmplitudeAPI.configure`.

**Comment by hult** [comment]
@kolorahl The current master doesn't have any provision for actually including whitelisted properties in  `Event#to_hash` though. Is the idea to add them both to the whitelist, then to something similar to `revenue_hash`, then to merge with that in `to_hash`?

**Comment by kolorahl** [comment]
@hult This is one of the reasons I haven't tried to cut a new version for release. I'm trying to figure out what the next step is to get this working in a sane manner, and I think I might go down the path of no whitelisting whatsoever (just blacklist the small set of known Amplitude-reserved event names) and then let the Amplitude API figure out what's good and what isn't and then the developer can handle any errors that crop up. On the one hand, it means the gem would no longer catch mistakes on the part of the developer, on the other hand it means the developer would get full access to all potential fields including future ones.

**Comment by hult** [comment]
@kolorahl I think that sounds like the right approach! No/less need for upgrading the lib whenever there's a new property in the API etc.

**Comment by AlvaroMaceda** [comment]
Thank you for your contribution. Version 0.3.0, just released, adds the new API properties and the ability to use custom ones.

**Pull request closed without merging**
