### PR TITLE
Support `platform` and `country` event parameters

### PR DESCRIPTION
**Pull request by kolorahl**
In addition, this should fix the build issues with `Time.parse` not being a valid function (it's no longer part of the Ruby standard library).

### CODE REVIEW

**Comment by kolorahl** [comment]
@toothrot Managed to fix the specs (problem with `Time.parse`) but also making some substantial under-the-hood changes.

To reiterate the "why" from one of my commits, the overhead to adding optional top-level attributes, such as `device_id`, is too great in the code's present state. You need to add a line for the `attr_accessor`, then explicitly set it in `def initialize`, then ensure it's being added properly in `to_hash`, and so on. The new method allows top-level attributes to be specified in a `whitelist` config value, so adding or removing those is as simple as adding or removing the attribute names from that config setting.

There were also style complaints starting to appear from adding more code (logic complexity and line length chief among them), so cutting down on the raw number of lines of code is helping prevent failure cases due to style rules.

Would love to hear your thoughts on this new direction, if you like it or not, what kind of changes you'd like to see, or if the whole thing should be scraped.

**Comment by jorilallo** [comment]
Was also looking for ability to add `platform` so would love to see this getting merged

**Comment by kolorahl** [comment]
For anyone watching this thread, I'm going to be releasing [my own version](https://gitlab.com/kolorahl/amplitude) of an Amplitude API wrapper gem. Presently it uses HTTParty because that was the fastest route to go, but soon I'll be replacing that with Faraday and Typhoeus as a performance improvement. I'd much rather contribute to an existing project and community but it feels like the development on this project has slowed significantly, maybe completely. Perhaps in the near future this project could add maintainers to help curate change requests such as this and keep it relevant and updated (I wouldn't mind nominating myself as a potential maintainer if this project goes that route).

**Comment by toothrot** [comment]
@kolorahl I'd love to add you as a maintainer. I haven't used Amplitude in a while, so let me set that up.

**Comment by kolorahl** [comment]
@toothrot Thanks!

**Pull request merged**
