### PR TITLE
Add session_id to optional properties

### PR DESCRIPTION
**Pull request by ceritium**
Allow send session_id to Amplitude API

### CODE REVIEW

**Comment by ceritium** [comment]
The tests are failing because `Time.parse` but it doesn't look related to my PR.
The branch 'master' is failing in local also, but with `bundle exec rspec` it works.

**Comment by toothrot** [comment]
Hey @ceritium! Thanks for the submission. I'll check out CI and see whats up.

**Comment by toothrot** [comment]
Hey @ceritium, does the property whitelist make this obsolete now?

**Comment by ceritium** [comment]
Sorry, I have no idea, I opened this PR long ago and I am not using amplitude any more. 

I am going to close this PR.

**Pull request closed without merging**
