### PR TITLE
Extand Faraday Version

### PR DESCRIPTION
**Pull request by Fcukit**
Now available Faraday [2.2.0](https://github.com/lostisland/faraday/releases/tag/v2.2.0). 
Let's update dependency ;)

### CODE REVIEW

**Comment by AlvaroMaceda** [comment]
Thanks a lot, Fcukit. This week and maybe the next I'll be super busy, but I'll try to check if everything works OK with the new Faraday version and will publish a new version ASAP.

**Comment by arrowcircle** [comment]
any news on updating dependency?

**Comment by Jonakemon** [comment]
@AlvaroMaceda anything we can help you with to get this deployd? :)

**Comment by AlvaroMaceda** [comment]
Sorry, guys, missed this one. I'll publish a new version this afternoon.

**Pull request merged**
